"""crear tabla leagues

Revision ID: 017a6cdb2b13
Revises: c51b15d41886
Create Date: 2026-08-19 16:06:06.616775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017a6cdb2b13'
down_revision: Union[str, Sequence[str], None] = 'c51b15d41886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('season', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leagues_unique_name_season', 'leagues', [sa.literal_column('lower(trim(name))'), sa.literal_column('lower(trim(season))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leagues_unique_name_season', table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
